Repository AY2021S1-CS2113T-T12-2/tp, pull requests merged in 2020-10, with the labels that each got.

#20 Add exam task
  data/tasks.txt
  src/main/java/seedu/duke/DateTimeParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
  src/main/java/seedu/duke/task/Exam.java
  src/main/java/seedu/duke/task/Lab.java
  src/main/java/seedu/duke/task/Lecture.java
  src/main/java/seedu/duke/task/Todo.java
  src/main/java/seedu/duke/task/Tutorial.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#27 Calendar superclass branch
  data/tasks.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/calendar/CalendarItem.java
  src/main/java/seedu/duke/calendar/CalendarList.java
  src/main/java/seedu/duke/calendar/event/Activity.java
  src/main/java/seedu/duke/calendar/event/Event.java
  src/main/java/seedu/duke/calendar/event/Lecture.java
  src/main/java/seedu/duke/calendar/event/SchoolEvent.java
  src/main/java/seedu/duke/calendar/task/Deadline.class
  src/main/java/seedu/duke/calendar/task/Deadline.java
  src/main/java/seedu/duke/calendar/task/Event.class
  src/main/java/seedu/duke/calendar/task/Exam.java
  src/main/java/seedu/duke/calendar/task/Lab.java
  src/main/java/seedu/duke/calendar/task/Task.class
  src/main/java/seedu/duke/calendar/task/Task.java
  src/main/java/seedu/duke/calendar/task/TaskList.class
  src/main/java/seedu/duke/calendar/task/Todo.class
  src/main/java/seedu/duke/calendar/task/Todo.java
  src/main/java/seedu/duke/calendar/task/Tutorial.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/DoneCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/PrintEventsCommand.java
  src/main/java/seedu/duke/command/PrintListCommand.java
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
  src/main/java/seedu/duke/command/ProgressCommand.java
  src/main/java/seedu/duke/task/Event.java
  src/main/java/seedu/duke/task/Exam.java
  src/main/java/seedu/duke/task/TaskList.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High

#29 Updated timeline command. Changes in Calendar Object needed.
  src/main/java/seedu/duke/Parser.class
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/calendar/CalendarItem.java
  src/main/java/seedu/duke/calendar/CalendarList.java
  src/main/java/seedu/duke/calendar/task/Deadline.java
  src/main/java/seedu/duke/calendar/task/Exam.java
  src/main/java/seedu/duke/calendar/task/Lab.java
  src/main/java/seedu/duke/calendar/task/Task.class
  src/main/java/seedu/duke/calendar/task/Task.java
  src/main/java/seedu/duke/calendar/task/TaskList.class
  src/main/java/seedu/duke/calendar/task/Todo.java
  src/main/java/seedu/duke/calendar/task/Tutorial.java
  src/main/java/seedu/duke/command/PrintTimelineCommand.class
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/tasks.txt
  text-ui-test/input.txt
Labels: priority.Medium, type.Bug

#36 Fix printEventsCommand and checkstyles
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/PrintEventsCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Low, severity.Low, type.Bug

#31 Update storage
  data/tasks.txt
  src/main/java/data/tasks.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/calendar/CalendarList.java
  src/main/java/seedu/duke/calendar/event/Activity.java
  src/main/java/seedu/duke/calendar/event/Lab.java
  src/main/java/seedu/duke/calendar/event/Lecture.java
  src/main/java/seedu/duke/calendar/event/Tutorial.java
  src/main/java/seedu/duke/calendar/task/Exam.java
  src/main/java/seedu/duke/command/AddCommand.java
  text-ui-test/data/tasks.txt
Labels: priority.Medium, severity.Medium, type.Task

#39 Update Duke Chat Box width
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.Low

#40 Finished Timeline Command
  src/main/java/seedu/duke/calendar/CalendarItem.java
  src/main/java/seedu/duke/calendar/event/Activity.java
  src/main/java/seedu/duke/calendar/event/Lab.java
  src/main/java/seedu/duke/calendar/event/Lecture.java
  src/main/java/seedu/duke/calendar/event/SchoolEvent.java
  src/main/java/seedu/duke/calendar/event/Tutorial.java
  src/main/java/seedu/duke/calendar/task/Task.java
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/tasks.txt
  text-ui-test/input.txt
Labels: priority.Medium, type.Task

#45 fix typo
  data/tasks.txt
  src/main/java/seedu/duke/Ui.java
Labels: severity.VeryLow

#48 Fixed bugs in printTimelineCommand
  src/main/java/seedu/duke/calendar/CalendarList.java
  src/main/java/seedu/duke/calendar/event/Activity.java
  src/main/java/seedu/duke/calendar/event/Exam.java
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Bug

#61 Updated timeline format (prints todo items also )
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, severity.Low, type.Enhancement

#77 Countdown feature
  data/tasks.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/calendar/event/Activity.java
  src/main/java/seedu/duke/calendar/event/Event.java
  src/main/java/seedu/duke/calendar/event/Exam.java
  src/main/java/seedu/duke/calendar/event/Lab.java
  src/main/java/seedu/duke/calendar/event/Lecture.java
  src/main/java/seedu/duke/calendar/event/Tutorial.java
  src/main/java/seedu/duke/calendar/task/Deadline.java
  src/main/java/seedu/duke/command/CountdownCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Story

#87 Add Junit for countdown command
  src/test/java/seedu/duke/command/CountdownCommandTest.java
Labels: priority.Medium

#90 Update storage for add info and priority
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/calendar/event/Activity.java
  src/main/java/seedu/duke/calendar/event/Exam.java
  src/main/java/seedu/duke/calendar/event/Lab.java
  src/main/java/seedu/duke/calendar/event/Lecture.java
  src/main/java/seedu/duke/calendar/event/Tutorial.java
  src/main/java/seedu/duke/calendar/task/Deadline.java
  src/main/java/seedu/duke/calendar/task/Todo.java
Labels: priority.Medium

#104 update readme.md in docs
  docs/AboutUs.md
  docs/README.md
Labels: priority.Medium, type.Task

#107 update user guide
  docs/README.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#116 Fixed format in DG, added links
  docs/DeveloperGuide.md
Labels: type.Bug

#122 Update welcome logo and chat box
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#124 add more assertion
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/PrintEventsCommandTest.java
  src/test/java/seedu/duke/command/PrintTasksCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#131 Enhanced the Module Checker class
  build.gradle
  data/tasks.txt
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/ModuleChecker.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/resources/ModuleChecker.java
  src/main/java/seedu/duke/resources/NusModule.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#132 add module checker to lect lab and tutorial.
  build.gradle
  data/tasks.txt
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
Labels: priority.Medium, type.Task

#148 update on DG and enable emoji plug in
  data/tasks.txt
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/images/JDK_Config_Screenshot.png
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/calendar/task/Deadline.java
Labels: type.Task

#149 DG for setting up
  docs/DeveloperGuide.md
  docs/images/Verify_setup.PNG
Labels: type.Task

#164 update DG on print tasks and print events
  docs/DeveloperGuide.md
  docs/images/PrintEventsCommand_SD.png
  docs/images/PrintTasksCommand_SD.png
Labels: type.Task

#168 Fix bugs of countdown command
  data/tasks.txt
  src/main/java/seedu/duke/command/CountdownCommand.java
Labels: priority.High, type.Bug

#169 Update user guide
  docs/UserGuide.md
Labels: priority.Medium

#170 update on DG
  docs/DeveloperGuide.md
Labels: type.Task

#172 update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  images/Help_Command.PNG
  images/JDK_Config_Screenshot.png
  images/PrintEventsCommand_SD.png
  images/PrintTasksCommand_SD.png
  images/Table1_legeng.PNG
  images/Verify_setup.PNG
  images/deadline_command.png
  images/tip_for_todo.PNG
  images/tips_deadline.PNG
  images/todo_command.png
  images/warning_deadline.PNG
  images/warning_help_command.PNG
Labels: priority.Medium

#185 update DG
  docs/DeveloperGuide.md
  docs/images/Verify_setup.PNG
Labels: priority.Medium, type.Task

#186 Add storage for developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#189 update DG
  docs/DeveloperGuide.md
  docs/images/PrintEventsCommand_SD.png
  docs/images/PrintTasksCommand_SD.png
Labels: priority.Medium, type.Bug, type.Task

#230 UG bug fixing test
  docs/UserGuide.md
Labels: type.Bug, type.Task

#231 fix Bug in TOC link
  docs/UserGuide.md
Labels: priority.Medium, type.Bug, type.Task

#232 Standardize TOC naming and fix bug on input example for lab events
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#233 update UG to correct invalid module code
  data/tasks.txt
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#234 update a reminder in UG:
  data/tasks.txt
  docs/UserGuide.md
Labels: severity.Low, type.Bug

#235 Add notes on school events
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug

#236 update typo in UG
  docs/UserGuide.md
Labels: type.Bug, type.Task

#237 reordered content.
  docs/UserGuide.md
Labels: type.Bug

#238 update table of legend figure
  docs/images/Table1_legeng.PNG
Labels: severity.Low, type.Bug

#239 update typo in UG
  docs/UserGuide.md
Labels: severity.Low
