Repository AY2021S1-CS2113T-T12-2/tp, pull requests merged in 2020-11, with the labels that each got.

#240 add due_date checker for deadline class
  src/main/java/seedu/duke/calendar/task/Deadline.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Enhancement, type.Task

#241 update deadline with new message for past deadline
  src/main/java/seedu/duke/Main.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/calendar/task/Deadline.java
  src/main/java/seedu/duke/command/AddCommand.java
Labels: type.Task

#242 fix invalid recurring number
  src/main/java/seedu/duke/command/AddCommand.java
Labels: severity.High, type.Bug, type.Enhancement, type.Task

#246 update on module checker
  NUS_Mod_info.json
  data/tasks.txt
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/resources/ModuleChecker.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Task

#247 PPP draft
  docs/team/LIU-YiFeng-1.md
Labels: type.Task

#250 update UG
  docs/UserGuide.md
  src/main/java/seedu/duke/Ui.java
Labels: priority.Medium, severity.Medium, type.Task

#251 Modify storage to accept empty additional information
  src/main/java/seedu/duke/Storage.java
Labels: priority.Medium, type.Bug

#253 Modified timeline feature in UG
  docs/UserGuide.md
  docs/team/Jingming517.md
Labels: type.Bug

#254 Fixed user input bugs in timeline
  data/tasks.txt
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
Labels: priority.Medium, type.Bug

#266 update UG
  data/tasks.txt
  docs/UserGuide.md
  docs/images/Help_Command.PNG
  docs/images/deadline_command.png
  docs/images/deadline_command_proper.png
Labels: priority.Medium, type.Task

#270 fix bug in Module_Checker
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
Labels: priority.High, severity.High, type.Bug

#277 update UG with expected output
  docs/UserGuide.md
  docs/images/additional_info_command.PNG
  docs/images/countdown_deadlines_command.PNG
  docs/images/countdown_exam_command.PNG
  docs/images/delete_additional_info_command.PNG
  docs/images/delete_event_command.PNG
  docs/images/delete_task_command.PNG
  docs/images/exam_command.PNG
  docs/images/find_event_command.PNG
  docs/images/find_item_command.PNG
  docs/images/find_task_command.PNG
  docs/images/lab_command.PNG
  docs/images/lect_command.PNG
  docs/images/prioritizing_command.PNG
  docs/images/tut_command.PNG
  docs/images/view_addit_info_command.PNG
Labels: priority.Medium, severity.Medium, type.Task

#284 update UG and DG
  data/tasks.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UML for DG-ModuleChecker.png
Labels: type.Task

#292 Fixed user input bugs in timeline
  src/main/java/seedu/duke/command/PrintTimelineCommand.java
Labels: type.Bug

#296 update UG_ready for final checks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Help_Command.PNG
  docs/images/find_event_command.PNG
  docs/images/printEvents_command.png
  docs/images/printTimeline_date_command.PNG
  docs/images/printTimeline_month_command.PNG
  docs/images/printTimeline_week_command.PNG
  docs/images/savingdata.png
  docs/images/tip_find.PNG
  docs/images/tip_find_event.PNG
  docs/images/tip_printEvents.PNG
  docs/team/johndoe.md
  src/main/java/seedu/duke/Ui.java
Labels: type.Task

#311 refactor image package
  data/tasks.txt
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/Archi_SD.JPG
  docs/images/Model_Class_Diagram.JPG
  docs/images/Overall_Architecture.JPG
  docs/images/PrintPriorityCommand_SD.png
  docs/images/PrintProgressCommand_SD.png
  docs/images/PrintSuggestionCommand_SD.png
  docs/images/PrintTimelineCommand_SD.png
  docs/images/PrioritizeCommand_SD.png
  docs/images/Verify_setup.PNG
  docs/images/addInfoCommand_SD.JPG
  docs/images/add_command_SD.JPG
  docs/images/add_command_date_SD.JPG
  docs/images/add_command_module_SD.JPG
  docs/images/command.JPG
  docs/images/countdown_command_SD.jpg
  docs/images/countdown_deadlines_exams_SD.jpg
  docs/images/deleteCommand_SD.JPG
  docs/images/deleteInfoCommand_SD.JPG
  docs/images/done_command_SD.JPG
  docs/images/findCommand_SD.JPG
  docs/images/storage_load_data_SD.jpg
  docs/images/storage_store_data_SD.jpg
  docs/images/viewInfoCommand_SD.JPG
  docs/team/LIU-YiFeng-1.md
Labels: type.Task
